/**
 * Port interface for the manual-review queue repository.
 *
 * Core Domain owns this port so ManualReviewService depends on an
 * abstraction, not a specific database adapter. The concrete adapter lives
 * in the composition root (DataPlatform).
 *
 * @module ManualReviewRepositoryPort
 */

import type { PendingReview, ReviewResolution, ReviewStatus } from '../manual-review.types';

/** Injection token for the manual-review repository port. */
export const MANUAL_REVIEW_REPOSITORY_PORT = 'MANUAL_REVIEW_REPOSITORY_PORT';

/**
 * Repository contract for the manual-review queue.
 *
 * The implementation is expected to persist entries in SQLite (or another
 * datastore) keyed by review id.
 */
export interface IManualReviewRepository {
  /**
   * Persist a new pending-review entry.
   * The id is expected to be generated by the caller (e.g. UUID).
   */
  create(entry: PendingReview): Promise<void>;

  /**
   * Retrieve a single pending-review entry by id.
   * Returns null when no entry with this id exists.
   */
  findById(id: string): Promise<PendingReview | null>;

  /**
   * Return all entries matching the given status, ordered by createdAt
   * descending (newest first).
   */
  findByStatus(status: ReviewStatus): Promise<PendingReview[]>;

  /**
   * Update the status and resolution of an existing review entry.
   * Called when a human operator resolves a pending review.
   */
  updateStatus(
    id: string,
    status: ReviewStatus,
    resolution?: ReviewResolution,
    resolvedAt?: string,
  ): Promise<void>;
}