/**
 * D1 GroupOrderRepository — shareable cost-splitting sessions and their
 * participant item lines (task 9.1, change
 * product-roadmap-phases-1-4, design R12), backed by the
 * `group_order_sessions` + `group_order_items` tables. Co-located
 * abstract + concrete (price-alert precedent — a D1-only table pair
 * with no pg counterpart).
 *
 * ACCOUNTING-ONLY BOUNDARY (spec: group-order-ledger): this repository
 * moves session and item rows only. It accepts no amounts, currencies,
 * payment instruments, or settlement state — and none can be smuggled
 * in, because the tables carry no column that could hold one (design
 * R12: the boundary is enforced at the schema level). Item VALUE for
 * the proportional allocation is resolved from product/offer data at
 * compute time (tasks 9.2/9.3), never through this contract.
 *
 * Expiry-read semantics (documented decision): `findByShareToken` and
 * `findSessionById` return the row whether or not its expiry edge has
 * passed, wrapped with an explicit `expired` flag evaluated against the
 * caller's `now` instant. The repository exposes the data honestly; it
 * deliberately does NOT refuse expired sessions — enforcement (the
 * expired-token rejection of spec scenario "Expired token rejected")
 * is the API layer's concern (task 9.3). `expiresAt` is an exclusive
 * edge: at exactly the expiry instant the session reads `expired`.
 * Unknown token/session → null, as usual.
 *
 * Participant anonymity: `participantNickname` is free text and the
 * ONLY participant identity these rows carry — participants join by
 * share link without an account (R12; content validation beyond the
 * 64-char bound belongs to the API's DTO layer).
 *
 * @module D1GroupOrderRepository
 */
import { Injectable } from '@nestjs/common';
import type { D1DatabaseLike } from '../../d1/executor';

/** Contract row — camelCase projection of the snake_case session row. */
export interface GroupOrderSessionRecord {
  readonly id: number;
  readonly ownerAccountId: number;
  /** The join credential — lookup key for the share link. */
  readonly shareToken: string;
  /** Exclusive expiry edge — at this instant the token is expired. */
  readonly expiresAt: Date;
  readonly createdAt: Date;
}

/** Contract row — one participant's line on a session. */
export interface GroupOrderItemRecord {
  readonly id: number;
  readonly sessionId: number;
  /** Self-chosen nickname — the only participant identity (anonymity by design). */
  readonly participantNickname: string;
  readonly productId: number;
  readonly quantity: number;
  readonly addedAt: Date;
}

/** Input for creating a session — the token is generated by the API layer, not here. */
export interface GroupOrderSessionInsert {
  readonly ownerAccountId: number;
  readonly shareToken: string;
  readonly expiresAt: string;
}

/** Input for one item line. */
export interface GroupOrderItemInsert {
  readonly sessionId: number;
  readonly participantNickname: string;
  readonly productId: number;
  readonly quantity: number;
}

/** A session plus its expiry state at the read's `now` instant. */
export interface GroupOrderSessionView {
  readonly session: GroupOrderSessionRecord;
  /** True when the expiry edge has passed — enforcement is the API's concern, not the repository's. */
  readonly expired: boolean;
}

/** Per-participant rollup — the session page's participant list (task 9.4). */
export interface GroupOrderParticipantSummary {
  readonly participantNickname: string;
  readonly itemCount: number;
  /** First line the nickname added — the join order's anchor. */
  readonly firstAddedAt: Date;
  readonly lastAddedAt: Date;
}

/**
 * Group order session + item contract (spec: group-order-ledger),
 * shared by the session API (task 9.3) and the compute path it backs.
 * The create path is owner-bound; participants never touch an account.
 */
@Injectable()
export abstract class GroupOrderRepository {
  /**
   * Create a session for the authenticated owner. Rejects on the share
   * token's unique constraint (token generation is the API layer's job —
   * a collision surfaces instead of being retried here).
   */
  abstract createSession(input: GroupOrderSessionInsert): Promise<GroupOrderSessionRecord>;

  /** Owner/compute-scope read by session id — expiry-aware view, null when absent. */
  abstract findSessionById(id: number, now?: Date): Promise<GroupOrderSessionView | null>;

  /** The share link's unique lookup — expiry-aware view, null when the token matches no session. */
  abstract findByShareToken(shareToken: string, now?: Date): Promise<GroupOrderSessionView | null>;

  /**
   * Append a participant's line to a session. Deliberately NOT
   * expiry-aware — the API checks expiry via the token read before
   * calling; the repository keeps the write path honest and single-purpose.
   * Rejects on unknown session/product (FK) or quantity ≤ 0 (CHECK).
   */
  abstract addItem(item: GroupOrderItemInsert): Promise<GroupOrderItemRecord>;

  /** All of one session's lines in ledger order: addedAt, then id for ties (deterministic). */
  abstract listItems(sessionId: number): Promise<GroupOrderItemRecord[]>;

  /** Per-participant rollup in join order (firstAddedAt, nickname tiebreak) — the participant list read. */
  abstract listParticipants(sessionId: number): Promise<GroupOrderParticipantSummary[]>;
}

/** Raw D1 group_order_sessions row. */
interface D1SessionRow {
  readonly id: number;
  readonly owner_account_id: number;
  readonly share_token: string;
  readonly expires_at: string;
  readonly created_at: string;
}

/** Raw D1 group_order_items row. */
interface D1ItemRow {
  readonly id: number;
  readonly session_id: number;
  readonly participant_nickname: string;
  readonly product_id: number;
  readonly quantity: number;
  readonly added_at: string;
}

/** Raw group_order_items aggregate row. */
interface D1ParticipantRow {
  readonly participant_nickname: string;
  readonly item_count: number;
  readonly first_added_at: string;
  readonly last_added_at: string;
}

function toContractSession(row: D1SessionRow): GroupOrderSessionRecord {
  return {
    id: row.id,
    ownerAccountId: row.owner_account_id,
    shareToken: row.share_token,
    expiresAt: new Date(row.expires_at),
    createdAt: new Date(row.created_at),
  };
}

function toContractItem(row: D1ItemRow): GroupOrderItemRecord {
  return {
    id: row.id,
    sessionId: row.session_id,
    participantNickname: row.participant_nickname,
    productId: row.product_id,
    quantity: row.quantity,
    addedAt: new Date(row.added_at),
  };
}

function toContractParticipant(row: D1ParticipantRow): GroupOrderParticipantSummary {
  return {
    participantNickname: row.participant_nickname,
    itemCount: row.item_count,
    firstAddedAt: new Date(row.first_added_at),
    lastAddedAt: new Date(row.last_added_at),
  };
}

/**
 * Expiry evaluation — `expiresAt` is the exclusive edge, so a session
 * read AT its expiry instant is expired ("past its expiry" per spec).
 */
function toSessionView(
  session: GroupOrderSessionRecord,
  now: Date,
): GroupOrderSessionView {
  return { session, expired: session.expiresAt.getTime() <= now.getTime() };
}

const SESSION_COLUMNS = `
  id, owner_account_id, share_token, expires_at, created_at`;

const ITEM_COLUMNS = `
  id, session_id, participant_nickname, product_id, quantity, added_at`;

const INSERT_SESSION_SQL = `
  INSERT INTO group_order_sessions (owner_account_id, share_token, expires_at)
  VALUES (?, ?, ?)
  RETURNING ${SESSION_COLUMNS}`;

const FIND_SESSION_BY_ID_SQL = `
  SELECT ${SESSION_COLUMNS} FROM group_order_sessions WHERE id = ?`;

const FIND_SESSION_BY_TOKEN_SQL = `
  SELECT ${SESSION_COLUMNS} FROM group_order_sessions WHERE share_token = ?`;

const INSERT_ITEM_SQL = `
  INSERT INTO group_order_items (session_id, participant_nickname, product_id, quantity)
  VALUES (?, ?, ?, ?)
  RETURNING ${ITEM_COLUMNS}`;

// addedAt then id: the deterministic ledger order — id breaks created-in
// the same millisecond ties.
const FIND_ITEMS_SQL = `
  SELECT ${ITEM_COLUMNS} FROM group_order_items
   WHERE session_id = ?
   ORDER BY added_at ASC, id ASC`;

const FIND_PARTICIPANTS_SQL = `
  SELECT participant_nickname, COUNT(*) AS item_count,
         MIN(added_at) AS first_added_at, MAX(added_at) AS last_added_at
    FROM group_order_items
   WHERE session_id = ?
   GROUP BY participant_nickname
   ORDER BY MIN(added_at) ASC, participant_nickname ASC`;

@Injectable()
export class D1GroupOrderRepository extends GroupOrderRepository {
  constructor(private readonly d1: D1DatabaseLike) {
    super();
  }

  /** @inheritdoc */
  async createSession(input: GroupOrderSessionInsert): Promise<GroupOrderSessionRecord> {
    const row = await this.d1
      .prepare(INSERT_SESSION_SQL)
      .bind(input.ownerAccountId, input.shareToken, input.expiresAt)
      .first<D1SessionRow>();
    if (!row) {
      throw new Error(
        `group_order_sessions insert for token "${input.shareToken}" returned no row`,
      );
    }
    return toContractSession(row);
  }

  /** @inheritdoc */
  async findSessionById(id: number, now: Date = new Date()): Promise<GroupOrderSessionView | null> {
    const row = await this.d1
      .prepare(FIND_SESSION_BY_ID_SQL)
      .bind(id)
      .first<D1SessionRow>();
    if (!row) {
      return null;
    }
    return toSessionView(toContractSession(row), now);
  }

  /** @inheritdoc */
  async findByShareToken(
    shareToken: string,
    now: Date = new Date(),
  ): Promise<GroupOrderSessionView | null> {
    const row = await this.d1
      .prepare(FIND_SESSION_BY_TOKEN_SQL)
      .bind(shareToken)
      .first<D1SessionRow>();
    if (!row) {
      return null;
    }
    return toSessionView(toContractSession(row), now);
  }

  /** @inheritdoc */
  async addItem(item: GroupOrderItemInsert): Promise<GroupOrderItemRecord> {
    const row = await this.d1
      .prepare(INSERT_ITEM_SQL)
      .bind(item.sessionId, item.participantNickname, item.productId, item.quantity)
      .first<D1ItemRow>();
    if (!row) {
      throw new Error(
        `group_order_items insert for session ${item.sessionId} returned no row`,
      );
    }
    return toContractItem(row);
  }

  /** @inheritdoc */
  async listItems(sessionId: number): Promise<GroupOrderItemRecord[]> {
    const { results } = await this.d1
      .prepare(FIND_ITEMS_SQL)
      .bind(sessionId)
      .all<D1ItemRow>();
    return results.map(toContractItem);
  }

  /** @inheritdoc */
  async listParticipants(sessionId: number): Promise<GroupOrderParticipantSummary[]> {
    const { results } = await this.d1
      .prepare(FIND_PARTICIPANTS_SQL)
      .bind(sessionId)
      .all<D1ParticipantRow>();
    return results.map(toContractParticipant);
  }
}
