/**
 * Port interface for the rate-review repository.
 *
 * Follows the same pattern as IManualReviewRepository in core-domain but
 * specialised for rate-review entries (which have different semantics than
 * product-matching review entries).
 *
 * The concrete adapter lives in the composition root (DataPlatform) and
 * persists entries in SQLite (or another datastore) keyed by review id.
 *
 * @module RateReviewRepositoryPort
 */

import type { RateReviewEntry, RateReviewStatus, RateReviewResolution } from './rate-review.types';

/** Injection token for the rate-review repository port. */
export const RATE_REVIEW_REPOSITORY_PORT = 'RATE_REVIEW_REPOSITORY_PORT';

/**
 * Repository contract for rate-review entries.
 *
 * Implementations persist RateReviewEntry objects and provide lookup by id
 * and status so the scheduler can create entries and operators can resolve them.
 */
export interface IRateReviewRepository {
  /**
   * Persist a new rate-review entry.
   * The id is expected to be generated by the caller (e.g. UUID).
   */
  create(entry: RateReviewEntry): Promise<void>;

  /**
   * Retrieve a single rate-review entry by id.
   * Returns null when no entry with this id exists.
   */
  findById(id: string): Promise<RateReviewEntry | null>;

  /**
   * Return all entries matching the given status, ordered by createdAt
   * descending (newest first).
   */
  findByStatus(status: RateReviewStatus): Promise<RateReviewEntry[]>;

  /**
   * Update the status and resolution of an existing rate-review entry.
   * Called when a human operator resolves a pending review.
   */
  updateStatus(
    id: string,
    status: RateReviewStatus,
    resolution?: RateReviewResolution,
    resolvedAt?: string,
    reviewerNotes?: string,
  ): Promise<void>;
}